// <auto-generated />
using System;
using EduCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduCore.API.Migrations
{
    [DbContext(typeof(EduCoreDbContext))]
    partial class EduCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduCore.API.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotificacionEnviada")
                        .HasColumnType("boolean");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SesionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioRegistroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.HasIndex("EstudianteId", "SesionId")
                        .IsUnique();

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("EduCore.API.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("AulaFisica")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grado")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("Grado", "Seccion", "PeriodoId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("EduCore.API.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalificacionOriginalId")
                        .HasColumnType("integer");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Recuperacion")
                        .HasColumnType("boolean");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RubroId");

                    b.HasIndex("EstudianteId", "RubroId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("EduCore.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaConocimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("boolean");

                    b.Property<int>("HorasSemana")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NivelGrado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("EduCore.API.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("EduCore.API.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AulaId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmailTutor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradoActual")
                        .HasColumnType("integer");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreTutor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ObservacionesMedicas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SeccionActual")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoTutor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("EduCore.API.Models.GrupoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<int?>("AulaId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("integer");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("Grado")
                        .HasColumnType("integer");

                    b.Property<string>("Horario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CursoId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("PeriodoId");

                    b.ToTable("GruposCursos");
                });

            modelBuilder.Entity("EduCore.API.Models.HorarioAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AulaId")
                        .HasColumnType("integer");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("AulaId", "DiaSemana", "HoraInicio")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("HorariosAulas");
                });

            modelBuilder.Entity("EduCore.API.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoCursoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PromedioFinal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCursoId");

                    b.HasIndex("EstudianteId", "GrupoCursoId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("EduCore.API.Models.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsActual")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Trimestre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EsActual")
                        .IsUnique()
                        .HasFilter("\"EsActual\" = true");

                    b.HasIndex("Nombre", "Trimestre");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("EduCore.API.Models.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("GrupoCursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCursoId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("EduCore.API.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoCursoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Realizada")
                        .HasColumnType("boolean");

                    b.Property<string>("Tema")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCursoId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("EduCore.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EstudianteId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@educore.com",
                            FechaCreacion = new DateTime(2025, 12, 4, 18, 57, 26, 607, DateTimeKind.Utc).AddTicks(4775),
                            NombreUsuario = "admin",
                            PasswordHash = "$2a$11$6OH.RnsaC9ClParDgk0eTeooIqWy2IodZNKfI4czuQOmr4lTeE0CO",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("EduCore.API.Models.Asistencia", b =>
                {
                    b.HasOne("EduCore.API.Models.Estudiante", "Estudiante")
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Sesion", "Sesion")
                        .WithMany("Asistencias")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("EduCore.API.Models.Aula", b =>
                {
                    b.HasOne("EduCore.API.Models.Periodo", "Periodo")
                        .WithMany("Aulas")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("EduCore.API.Models.Calificacion", b =>
                {
                    b.HasOne("EduCore.API.Models.Estudiante", "Estudiante")
                        .WithMany("Calificaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Rubro", "Rubro")
                        .WithMany("Calificaciones")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Rubro");
                });

            modelBuilder.Entity("EduCore.API.Models.Estudiante", b =>
                {
                    b.HasOne("EduCore.API.Models.Aula", "Aula")
                        .WithMany("Estudiantes")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Aula");
                });

            modelBuilder.Entity("EduCore.API.Models.GrupoCurso", b =>
                {
                    b.HasOne("EduCore.API.Models.Aula", "Aula")
                        .WithMany("GruposCursos")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EduCore.API.Models.Curso", "Curso")
                        .WithMany("GruposCursos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Docente", "Docente")
                        .WithMany("GrupoCursos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Periodo", "Periodo")
                        .WithMany("GruposCursos")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Curso");

                    b.Navigation("Docente");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("EduCore.API.Models.HorarioAula", b =>
                {
                    b.HasOne("EduCore.API.Models.Aula", "Aula")
                        .WithMany("Horarios")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("EduCore.API.Models.Inscripcion", b =>
                {
                    b.HasOne("EduCore.API.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.API.Models.GrupoCurso", "GrupoCurso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GrupoCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("GrupoCurso");
                });

            modelBuilder.Entity("EduCore.API.Models.Rubro", b =>
                {
                    b.HasOne("EduCore.API.Models.GrupoCurso", "GrupoCurso")
                        .WithMany("Rubros")
                        .HasForeignKey("GrupoCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoCurso");
                });

            modelBuilder.Entity("EduCore.API.Models.Sesion", b =>
                {
                    b.HasOne("EduCore.API.Models.GrupoCurso", "GrupoCurso")
                        .WithMany("Sesiones")
                        .HasForeignKey("GrupoCursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoCurso");
                });

            modelBuilder.Entity("EduCore.API.Models.Usuario", b =>
                {
                    b.HasOne("EduCore.API.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EduCore.API.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("EduCore.API.Models.Aula", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("GruposCursos");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("EduCore.API.Models.Curso", b =>
                {
                    b.Navigation("GruposCursos");
                });

            modelBuilder.Entity("EduCore.API.Models.Docente", b =>
                {
                    b.Navigation("GrupoCursos");
                });

            modelBuilder.Entity("EduCore.API.Models.Estudiante", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("EduCore.API.Models.GrupoCurso", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Rubros");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("EduCore.API.Models.Periodo", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("GruposCursos");
                });

            modelBuilder.Entity("EduCore.API.Models.Rubro", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("EduCore.API.Models.Sesion", b =>
                {
                    b.Navigation("Asistencias");
                });
#pragma warning restore 612, 618
        }
    }
}
